### PR TITLE
Prm 200 add widget language support

### PR DESCRIPTION
**Pull request by c-wright**
@fongstanley 
@chunpi 
@bertrandvidal 
@jtaoct 
@georgehlim 
@matthewsheahan

### CODE REVIEW

**Comment by c-wright** [comment]
I'm just parsing the query string {code}window.location.search{code}, not the entire URL. We should know all of the keys in the query string, "time saving" on this is negligible.

**Comment by bertrandvidal** [comment]
OK - correct typo though

**Comment by c-wright** [comment]
fixed typo

**Comment by c-wright** [comment]
Can you guys take a quick look when you can
@fongstanley 
@chunpi 
@bertrandvidal 
@jtaoct 
@georgehlim 
@matthewsheahan

**Comment by bertrandvidal** [comment]
:+1:

**Pull request merged**
